-- Staging leases: what lets cleanup remove an abandoned upload without
-- ever removing one that is still in progress (item 6 design, D6).
--
-- ADR 0027 forbids destructive recovery that removes another actor's
-- in-progress work, and "the writer's promote will fail afterwards" is not
-- a mitigation. Nor is a timer: a writer paused past its term resumes
-- believing it still holds the staging object, and by then cleanup may have
-- deleted it -- or another writer may have created a different object at
-- the same key.
--
-- Three mechanisms answer three different questions, and only two of them
-- are columns:
--
--   * EXPIRY decides when cleanup may CONSIDER a lease abandoned;
--   * the OWNER TOKEN decides whether a writer may still PROMOTE;
--   * the ROW LOCK decides who acts first when both are live at once --
--     a property of how these rows are read, not of the schema. The
--     promoting transaction holds `SELECT ... FOR UPDATE` on the lease
--     across the ownership check, the promote, the read-back and the
--     attachment insert; cleanup takes the same lock and rechecks expiry
--     under it, so it either waits or finds the lease alive.
BEGIN;

CREATE TABLE staging_leases (
    staging_lease_id uuid        PRIMARY KEY,
    organization_id  uuid        NOT NULL REFERENCES organizations (organization_id) ON DELETE RESTRICT,

    -- The key this lease covers, in the EXACT shape D3 defines:
    -- `staging/<organization_id>/<uuid>`, and nothing else.
    --
    -- Cleanup enumerates and DELETES every version under this key, and
    -- aborts every upload on it, so what may be written here is
    -- constrained rather than trusted. Three ways a looser rule goes
    -- wrong, all of which a prefix match with a trailing wildcard admits:
    --
    --   * a DIGEST key would point that deletion at content-addressed
    --     evidence;
    --   * ANOTHER organization's staging key would point it across the
    --     tenant boundary, which is why the pattern is built from this
    --     row's own organization rather than from a constant;
    --   * a key that is a PREFIX of other keys — `staging/<org>/` itself,
    --     or `staging/<org>/upload` beside `staging/<org>/upload-1` —
    --     would take out every sibling upload with it, because the
    --     enumeration cleanup performs is prefix-based. A fixed-length
    --     uuid segment closes this by construction: no key of this shape
    --     can be a prefix of another.
    --
    -- The uuid's version nibble is deliberately unconstrained. What this
    -- has to guarantee is one path segment of fixed length, not which
    -- generator produced it.
    staging_key      text        NOT NULL,

    -- Generated by the writer before the first byte.
    --
    -- Renewal moves expires_at only where the row still carries THIS token
    -- and has not expired. Zero rows updated means the lease is lost and
    -- the writer aborts; there is no re-insert, so a lease cannot be
    -- resurrected by the actor that lost it.
    owner_token      uuid        NOT NULL,

    created_at       timestamptz NOT NULL DEFAULT now(),
    expires_at       timestamptz NOT NULL,

    CONSTRAINT staging_leases_key_scope_check
        CHECK (staging_key ~ ('^staging/' || organization_id::text ||
            '/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')),
    CONSTRAINT staging_leases_term_check
        CHECK (expires_at > created_at),

    -- One lease per staging key. Two live writers on one key is the state
    -- the lease exists to make impossible, and this index is also what a
    -- promoting transaction locks the row through.
    CONSTRAINT staging_leases_key_unique UNIQUE (organization_id, staging_key)
);

-- Cleanup's only read: one organization's expired leases. No index for
-- lookup by key -- the unique constraint above already serves it.
CREATE INDEX staging_leases_org_expiry_idx ON staging_leases (organization_id, expires_at);

COMMIT;
