linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "orchestrator/pkg/agent/internal/**"
            desc: "do not import agent internals from outside pkg/agent"
        allow:
          - $all
        list-type: denylist
      
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters: [depguard]
    - path: pkg/agent/.*\.go
      linters: [depguard]  # Allow internal imports within pkg/agent

linters:
  enable:
    - depguard
    - goimports
    - gosec
    - govet