version: 2
project_name: maestro

before:
  hooks:
    - go mod tidy

builds:
  - id: maestro
    main: ./cmd/maestro
    binary: maestro
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        # Sign macOS binaries immediately after build (before archiving)
        - cmd: |
            sh -c '
            if [ "{{ .Os }}" = "darwin" ]; then
              echo "Signing {{ .Path }}"
              codesign --force --options runtime --timestamp \
                --sign "Developer ID Application: Snapdragon Partners LLC (VNJH3VB68C)" "{{ .Path }}"
            fi
            '
          output: true

archives:
  - formats: ['tar.gz']
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: SnapdragonPartners
    name: maestro

changelog:
  use: git

homebrew_casks:
  - name: maestro
    directory: Casks
    repository:
      owner: SnapdragonPartners
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Maestro CI
      email: maestro@snapdragonpartners.com
    homepage: "https://github.com/SnapdragonPartners/maestro"
    description: "Multi-agent AI coding system orchestrator"
    binaries:
      - maestro
