version: 2
project_name: maestro

before:
  hooks:
    - go mod tidy
    # Build MCP proxy binaries for embedding (must run before main build)
    - mkdir -p pkg/coder/claude/embedded
    - sh -c 'CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o pkg/coder/claude/embedded/proxy-linux-arm64 ./cmd/maestro-mcp-proxy'
    - sh -c 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o pkg/coder/claude/embedded/proxy-linux-amd64 ./cmd/maestro-mcp-proxy'

builds:
  - id: maestro
    main: ./cmd/maestro
    binary: maestro
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X orchestrator/pkg/version.Version={{.Version}}
      - -X orchestrator/pkg/version.Commit={{.Commit}}
      - -X orchestrator/pkg/version.Date={{.Date}}
    hooks:
      post:
        # Sign macOS binaries immediately after build (before archiving)
        - cmd: |
            sh -c '
            if [ "{{ .Os }}" = "darwin" ]; then
              echo "Signing {{ .Path }}"
              codesign --force --options runtime --timestamp \
                --sign "Developer ID Application: Snapdragon Partners LLC (VNJH3VB68C)" "{{ .Path }}"
            fi
            '
          output: true

archives:
  # Use zip for macOS (required for notarization), tar.gz for Linux
  - formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: linux
        formats: ['tar.gz']

nfpms:
  - id: maestro-deb
    package_name: maestro
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Snapdragon Partners LLC
    homepage: https://github.com/SnapdragonPartners/maestro
    maintainer: Snapdragon Partners <maestro@snapdragonpartners.com>
    description: Multi-agent AI coding system orchestrator
    license: MIT
    formats:
      - deb
    bindir: /usr/local/bin

release:
  github:
    owner: SnapdragonPartners
    name: maestro

changelog:
  use: git

homebrew_casks:
  - name: maestro
    directory: Casks
    repository:
      owner: SnapdragonPartners
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Maestro CI
      email: maestro@snapdragonpartners.com
    homepage: "https://github.com/SnapdragonPartners/maestro"
    description: "Multi-agent AI coding system orchestrator"
    binaries:
      - maestro
