# Generated by Claude Code Bootstrap
# This file contains agent-generated build targets
# Backend: go

.PHONY: build test lint run

build:
	go mod download
	go build ./...

test:
	go test ./...

lint:
	@which golangci-lint > /dev/null || (echo "golangci-lint not found, using go vet" && go vet ./...)
	@which golangci-lint > /dev/null && golangci-lint run ./...

run:
	go run .
