# Generated by Claude Code Bootstrap
# This Makefile uses the include pattern to prevent merge conflicts
# Human-maintained targets should be added here
# Agent-generated targets are in agent.mk

# Include agent-generated targets
-include agent.mk

# Default targets if agent.mk doesn't exist
.PHONY: build test lint run help

build:
	@echo "No build configured. Run bootstrap to set up build system."

test:
	@echo "No tests configured. Run bootstrap to set up test system."

lint:
	@echo "No linting configured. Run bootstrap to set up linting system."

run:
	@echo "No run target configured. Run bootstrap to set up run system."

help:
	@echo "Available targets:"
	@echo "  build  - Build the project"
	@echo "  test   - Run tests"
	@echo "  lint   - Run linting"
	@echo "  run    - Run the application"
	@echo "  help   - Show this help message"
	@echo ""
	@echo "This project uses Claude Code Bootstrap for build management."
	@echo "Agent-generated targets are in agent.mk."
