# Generated by Claude Code Bootstrap
# This file contains agent-generated build targets
# Backend: null

.PHONY: build test lint run

# Unknown backend - providing basic targets
build:
	@echo "Build not configured for backend: null"

test:
	@echo "Tests not configured for backend: null"

lint:
	@echo "Linting not configured for backend: null"

run:
	@echo "Run not configured for backend: null"
