// Package maintenance provides maintenance mode templates and report generation.
package maintenance

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// CycleReport contains all data for a maintenance cycle report.
//
//nolint:govet // Field order for readability
type CycleReport struct {
	CycleID     string
	StartedAt   time.Time
	CompletedAt time.Time
	Duration    time.Duration

	// Programmatic results
	BranchesDeleted []string
	CleanupErrors   []string

	// Story results
	Stories []*StoryResult

	// Aggregated metrics
	Metrics CycleMetrics
}

// StoryResult tracks the result of a single maintenance story.
//
//nolint:govet // Field order for readability
type StoryResult struct {
	StoryID     string
	Title       string
	Status      string // completed, failed
	PRNumber    int
	PRMerged    bool
	CompletedAt time.Time
	Summary     string
}

// CycleMetrics aggregates metrics across a maintenance cycle.
type CycleMetrics struct {
	StoriesTotal     int
	StoriesCompleted int
	StoriesFailed    int
	PRsMerged        int
	BranchesDeleted  int
}

// reportTemplate defines the markdown template for maintenance reports.
const reportTemplate = `# Maintenance Report - {{.CycleID}}

**Started**: {{.StartedAt.Format "2006-01-02 15:04:05 UTC"}}
**Completed**: {{.CompletedAt.Format "2006-01-02 15:04:05 UTC"}}
**Duration**: {{formatDuration .Duration}}

---

## Programmatic Tasks

### Branch Cleanup
{{if .BranchesDeleted -}}
Deleted **{{len .BranchesDeleted}}** stale branches:
{{range .BranchesDeleted}}
- ` + "`{{.}}`" + `
{{end}}
{{- else -}}
No stale branches found.
{{- end}}

{{if .CleanupErrors -}}
**Errors encountered:**
{{range .CleanupErrors}}
- {{.}}
{{end}}
{{- end}}

---

## Story Results

{{if .Stories -}}
| Story | Status | PR | Merged |
|-------|--------|----|----|
{{range .Stories -}}
| {{.Title}} | {{statusEmoji .Status}} {{.Status}} | {{if .PRNumber}}#{{.PRNumber}}{{else}}-{{end}} | {{if .PRMerged}}Yes{{else}}No{{end}} |
{{end}}
{{- else -}}
No maintenance stories were executed.
{{- end}}

{{range .Stories}}
{{if .Summary -}}
### {{.Title}}
{{.Summary}}

{{end}}
{{- end}}

---

## Metrics Summary

| Metric | Value |
|--------|-------|
| Stories Total | {{.Metrics.StoriesTotal}} |
| Stories Completed | {{.Metrics.StoriesCompleted}} |
| Stories Failed | {{.Metrics.StoriesFailed}} |
| PRs Merged | {{.Metrics.PRsMerged}} |
| Branches Deleted | {{.Metrics.BranchesDeleted}} |

---

*Generated by Maestro Maintenance Mode*
`

// templateFuncs provides helper functions for the report template.
//
//nolint:gochecknoglobals // Template functions must be global for text/template
var templateFuncs = template.FuncMap{
	"statusEmoji": func(status string) string {
		switch status {
		case "completed":
			return "✅"
		case "failed":
			return "❌"
		default:
			return "⏳"
		}
	},
	"formatDuration": func(d time.Duration) string {
		if d < time.Minute {
			return fmt.Sprintf("%d seconds", int(d.Seconds()))
		}
		if d < time.Hour {
			return fmt.Sprintf("%d minutes", int(d.Minutes()))
		}
		hours := int(d.Hours())
		minutes := int(d.Minutes()) % 60
		return fmt.Sprintf("%d hours %d minutes", hours, minutes)
	},
}

// ToMarkdown generates a markdown report from the cycle data.
func (r *CycleReport) ToMarkdown() (string, error) {
	tmpl, err := template.New("report").Funcs(templateFuncs).Parse(reportTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse report template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, r); err != nil {
		return "", fmt.Errorf("failed to execute report template: %w", err)
	}

	return buf.String(), nil
}

// SaveToFile persists the report to a file in the specified directory.
func (r *CycleReport) SaveToFile(dir string) (string, error) {
	// Ensure directory exists
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create report directory: %w", err)
	}

	// Generate filename with timestamp
	filename := fmt.Sprintf("maintenance-report-%s.md", r.CycleID)
	filepath := filepath.Join(dir, filename)

	content, err := r.ToMarkdown()
	if err != nil {
		return "", err
	}

	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write report file: %w", err)
	}

	return filepath, nil
}

// NewCycleReport creates a report from maintenance tracking data.
// This is a helper to convert from architect's internal tracking format.
func NewCycleReport(
	cycleID string,
	startedAt time.Time,
	branchesDeleted []string,
	cleanupErrors []string,
	stories []*StoryResult,
	metrics CycleMetrics,
) *CycleReport {
	now := time.Now()
	return &CycleReport{
		CycleID:         cycleID,
		StartedAt:       startedAt,
		CompletedAt:     now,
		Duration:        now.Sub(startedAt),
		BranchesDeleted: branchesDeleted,
		CleanupErrors:   cleanupErrors,
		Stories:         stories,
		Metrics:         metrics,
	}
}
