// Code generated by "stringer -type=ArchitectState -trimprefix=State"; DO NOT EDIT.

package architect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateWaiting-0]
	_ = x[StateScoping-1]
	_ = x[StateDispatching-2]
	_ = x[StateMonitoring-3]
	_ = x[StateRequest-4]
	_ = x[StateEscalated-5]
	_ = x[StateMerging-6]
	_ = x[StateDone-7]
	_ = x[StateError-8]
}

const _ArchitectState_name = "WaitingScopingDispatchingMonitoringRequestEscalatedMergingDoneError"

var _ArchitectState_index = [...]uint8{0, 7, 14, 25, 35, 42, 51, 58, 62, 67}

func (i ArchitectState) String() string {
	if i < 0 || i >= ArchitectState(len(_ArchitectState_index)-1) {
		return "ArchitectState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchitectState_name[_ArchitectState_index[i]:_ArchitectState_index[i+1]]
}
